{{- if .Values.dataProcessor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-platform.fullname" . }}-data-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-processor
spec:
  type: {{ .Values.dataProcessor.service.type }}
  ports:
    - port: {{ .Values.dataProcessor.service.port }}
      targetPort: {{ .Values.dataProcessor.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "data-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: data-processor
{{- end }}
