apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: document-processor
  namespace: flux-system
spec:
  # Watches GHCR for new tags of this image
  image: ghcr.io/akshay007724/data-platform/document-processor
  interval: 1m
  secretRef:
    name: ghcr-flux-auth   # created in deploy.md step 4
