apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-platform.fullname" . }}-pipeline-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline-config
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ include "data-platform.kafkaBootstrap" . | quote }}
  RELEASE_NAME: {{ .Release.Name | quote }}
  CHART_VERSION: {{ .Chart.Version | quote }}
  {{- range $key, $value := .Values.pipelineConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
